name: Docker Build and Deploy 2

on:
  push:
    branches: [ "main" ]  # main 브랜치에 push가 발생할 때 실행
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # 수동 실행 가능

env:
  DOCKER_IMAGE: kschoi728/simple-web
  DOCKER_TAG: 0.2

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: 8.Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        logout: true
        
    - name: 9.Docker Push
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/istory:${{ env.DOCKER_TAG }}

      # 서비스 리포지토리 체크아웃
      - name: 10.서비스 리포지토리 체크아웃
        uses: actions/checkout@v4
        with:
          repository: kschoi728-naver/simple-service
          ref: main
          path: .
      
      # # 이미지 태그 업데이트
      # - name: 11.쿠버네티스 매니페스트 파일 이미지 태그 업데이트
      #   run: |
      #     # 파일이 존재하는지 확인
      #     ls -la
      #     # 현재 파일 내용 확인
      #     cat istory-app-deploy.yaml
      #     sed -i "s|image: ${{ secrets.DOCKER_USERNAME }}\/istory.*|image: ${{ secrets.DOCKER_USERNAME }}\/istory:${{ env.DOCKER_TAG }}|g" istory-app-deploy.yaml
      #     # 변경된 내용 확인
      #     cat istory-app-deploy.yaml
      
      # 변경사항 커밋 및 푸시
      - name: 12.서비스 리포지토리 변경사항 커밋 및 푸시
        run: |
          git config --global user.name 'kschoi728-naver' # 바꾸기
          git config --global user.email 'kschoi728@naver.com' # 바꾸기
          git commit -am "Update image tag to ${{ env.DOCKER_TAG }}"
          git remote set-url origin https://${{ secrets.PAT }}@github.com/dangtong-s-inc/istory-service.git # 바꾸기 
          
          git push origin main