name: Deploy Simple-Web to AWS EC2 using AWS CLI 22
on:
  push:
    branches:
      - main
jobs:
  deploys:
    runs-on: ubuntu-latest
    steps:
      - name: 1.소스코드 가져오기
        uses: actions/checkout@v3 #리포지토리의 소스 코드를 현재 워크플로우의 작업 환경으로 가져오는(checkout) 역할

      - name: 2.AWS 접속정보 설정
        uses: aws-actions/configure-aws-credentials@v3  #GitHub Actions에서 AWS(Amazon Web Services)에 안전하게 접근할 수 있도록 AWS 자격 증명을 설정하는 액션
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: 3.SSH Key 설정
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_KEY }}
          
      - name: 4.files 목록보기
        run: |
          ssh -o StrictHostKeyChecking=no \
          ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} \
          "ls -la /home/${{ secrets.AWS_USER }}"

      - name: 5.EC2에 파일 복사
        run: |
          ssh -o StrictHostKeyChecking=no \
          ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} \
          "sudo chown -R ec2-user:ec2-user /usr/share/nginx/html"
        
          scp -o StrictHostKeyChecking=no \
          -r ./* ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }}:/usr/share/nginx/html

      - name: 6.Web Server 재시작
        run: |
          ssh -v -o StrictHostKeyChecking=no \
          ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} \
          "sudo systemctl restart nginx || sudo systemctl restart httpd"